version: '3.2'
services:
  fiuba-laboral-v2-backend:
    build: .
    command: yarn dev
    image: fiuba-laboral-v2-backend-img
    container_name: "fiuba-laboral-v2-backend"
    ports:
      - 5000:5000
    volumes:
      - '.:/usr/src/app'
    depends_on:
      - fiuba-laboral-v2-backend-database-postgres
    environment:
      "NODE_ENV": "development"
  fiuba-laboral-v2-backend-database-postgres:
    image: postgres:latest
    container_name: "fiuba-laboral-v2-backend-database-postgres"
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: fiuba-laboral-v2-backend-database-postgres-development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: 127.0.0.1
      NODE_ENV: development
