apps:
  - script: ./dist/src/index.js 
    name: 'fiuba-laboral-v2-back-end'
    node_args: '-r ts-node/register -r tsconfig-paths/register'
    instances: max
    exec_mode: cluster
    watch: true
    max_memory_restart: 750M
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
    env_staging:
      NODE_ENV: staging
    env_test:
      NODE_ENV: test
