name: back-end-build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test_travis
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_travis
    services:
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      matrix:
        node-version: [14.15.0]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Database setup
        run: yarn db:drop || true && yarn db:create && yarn db:migrate
      - name: Run linter and tests
        run: yarn lint && yarn test
      - name: Coveralls
        run: yarn coverage
      - name: Trigger deploy workflow
        if: success() && contains('refs/heads/staging refs/heads/production', github.ref)
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_TOKEN }}
          repository: fiuba-laboral-v2/deploy
          event-type: backend-deploy
          client-payload: '{"stage": "${{ github.ref }}"}'
