name: back-end-deploy
on:
  workflow_run:
    workflows: ["back-end-build"]
    branches: [staging]
    types:
      - completed
      - requested
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI_DEPLOY_KEY: ${{ secrets.CI_DEPLOY_KEY }}
    strategy:
      matrix:
        node-version: [14.15.0]
    steps:
      - name: add ssh key
        run: eval "$(ssh-agent -s)" && ssh-add $CI_DEPLOY_KEY
      - name: Check out deploy repository code
        run: git clone https://github.com/fiuba-laboral-v2/deploy.git
      - name: Go to deploy directory
        run: cd deploy
      - name: Install dependencies
        run: yarn install
      - name: Run deploy script for ${GITHUB_REF##*/} environment
        run: NODE_ENV=${GITHUB_REF##*/} yarn deploy:backend
