name: back-end-deploy
on:
  push:
    branches:
      - staging
      - feature/github-actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI_DEPLOY_KEY: ${{ secrets.CI_DEPLOY_KEY }}
      CURRENT_BRANCH: ${GITHUB_REF##*/}
    strategy:
      matrix:
        node-version: [14.15.0]
    steps:
      - name: add ssh key
        run: eval "$(ssh-agent -s)" && ssh-add <(echo "$CI_DEPLOY_KEY")
      - name: Check out deploy repository code
        uses: actions/checkout@master
        with:
          repository: fiuba-laboral-v2/deploy
      - name: Install dependencies
        run: yarn install
      - name: Run deploy script for "$CURRENT_BRANCH" environment
        run: NODE_ENV=staging yarn deploy:backend
